# Generated by Django 4.0.4 on 2022-06-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=15)),
                ('photo', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('price', models.FloatField(max_length=15)),
            ],
        ),
    ]
