# Generated by Django 4.0.4 on 2022-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shoes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
